services: 
  postgres_drivenops_db: 
    image: postgres
    container_name: postgres_drivenops_db
    restart: always
    ports: 
      - 8000:5432
    env_file:
      - back-end/.env.test
    volumes:
      - pg_drivenops-db:/var/lib/postgresql/data

  node_drivenops:
    container_name: node_drivenops
    build: ./back-end 
    ports: 
      - 5000:5000
    depends_on:
      - postgres_drivenops_db
    env_file:
      - back-end/.env.test

volumes:
  pg_drivenops-db: